# Generated by Django 4.2.5 on 2023-09-20 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='time',
            field=models.TimeField(verbose_name='time for action'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='time_for_action',
            field=models.TimeField(blank=True, null=True, verbose_name='action duration'),
        ),
    ]
