# Generated by Django 4.2.5 on 2023-09-21 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0002_alter_habit_time_alter_habit_time_for_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='SenderDailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_send', models.CharField(choices=[('CREATE', 'create'), ('SENT', 'sent'), ('ERROR', 'sending error')], default='CREATE', max_length=6, verbose_name='sending status')),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habit.habit', verbose_name='habit id')),
            ],
            options={
                'verbose_name': 'log status',
                'verbose_name_plural': 'log statuses',
                'ordering': ['pk'],
            },
        ),
    ]
