# Generated by Django 4.2.5 on 2023-09-21 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0003_senderdailylog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='senderdailylog',
            old_name='is_send',
            new_name='daily_status',
        ),
    ]
