# Generated by Django 4.2.5 on 2023-09-21 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0004_rename_is_send_senderdailylog_daily_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='senderdailylog',
            name='habit',
        ),
        migrations.RemoveField(
            model_name='senderdailylog',
            name='id',
        ),
        migrations.AddField(
            model_name='senderdailylog',
            name='habit_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='habit.habit', verbose_name='habit id'),
        ),
    ]
